const CONTENT_MAP = {
  Machinery: {
    1: '\n<p>Hi {{$json.Name}},</p>\n\n<p>Following up briefly, because the expensive part is usually not the part anyone is looking at.</p>\n\n<p>The real cost in industrial machinery and equipment manufacturing businesses isn\u2019t the obvious spend. It is the work that never appears on a line item:</p>\n\n<p>\u2022 Custom quoting and configuration cycles stretch into days because specifications sit in spreadsheets, drawings and email threads that nobody can query.</p>\n\n<p>\u2022 Spare parts and service requests get handled manually, which slows response times and quietly leaks aftermarket revenue.</p>\n\n<p>\u2022 Engineers lose hours a week answering spec questions, hunting revisions of old drawings and looking up part numbers. None of it appears on a project plan, all of it comes out of build time.</p>\n\n<p>On their own, none of these look like a problem. Together they are a standing headcount cost, paid every month, for work that produces nothing. The same hours put into designing, building and shipping machines would show up directly in revenue.</p>\n\n<p>We build the fix for one of them first, free. You pay only when it is working in your business. No software license, nobody new to hire, and no new process for your team to run.</p>\n\n<p>Your competitors are already doing this. Every month it stays manual is a month they spend returning quotes in hours while the rest of the market still takes days.</p>\n\n<p>If you\u2019d like to explore what this could look like, feel free to grab a convenient time here: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n\n',
    2: '\n<p>Hi {{$json.Name}},</p>\n\n<p>Just checking in one more time.</p>\n\n<p>Many industrial machinery and equipment manufacturing businesses assume that shortening quote cycles and cutting manual engineering admin requires new software or a large transformation project. In reality, automating one repetitive process such as quotation and BOM preparation, spare parts and service ticket handling, and warranty and installation documentation saves hours every week. Quotes go out in hours instead of days and your engineers spend their time on machines rather than on documents.</p>\n\n<p>That capacity does not disappear, it moves. The people doing that work today go back to designing, building and shipping machines, which is where your return actually comes from.</p>\n\n<p>We\u2019re happy to identify one opportunity and build it for you at no cost. Nothing changes in how your team works, the output just arrives. You only move forward if it delivers value.</p>\n\n<p>The gap between businesses running on AI and businesses running on people isn\u2019t closing, it\u2019s widening. It widens quietly, which is what makes it easy to miss until a competitor prices or delivers in a way you cannot match.</p>\n\n<p>If you\u2019d like to explore one automation opportunity for your business, you can grab a slot on my calendar: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n\n\n',
    3: '\n<p>Hi {{$json.Name}},</p>\n\n<p>I understand this may not be the right time, so I\u2019ll close the loop for now.</p>\n\n<p>If shortening quote cycles and cutting manual engineering admin isn\u2019t a priority today, no worries. I just wanted to leave this with you in case it becomes relevant down the road.</p>\n\n<p>Whenever you\u2019re looking at practical AI automation that delivers measurable results without upfront cost, extra software or a new process to manage, we\u2019d be happy to help. We hand over the outcome, not another system for your team to run.</p>\n\n<p>AI in operations isn\u2019t a trend anymore, it\u2019s becoming the baseline. The businesses adopting it now won\u2019t simply be doing the same work faster. They will be operating on a cost base the rest of the market cannot match, and by the time that shows up in pricing it is difficult to catch.</p>\n\n<p>If you\u2019d ever like to chat, you can grab a time directly on my calendar here: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n\n',
  },
  Electric: {
    1: '<p>Hi {{Name}},</p>\n\n<p>Following up briefly, because the expensive part is usually not the part anyone is looking at.</p>\n\n<p>The real cost in electrical and electronic manufacturing businesses isn\u2019t the obvious spend. It is the work that never appears on a line item:</p>\n\n<p>\u2022 Certificates of conformance and supplier compliance docs get chased manually across email, which slows down shipments and audits alike.</p>\n\n<p>\u2022 Rework, scrap and non-conformance logging happens on paper or scattered spreadsheets, so nobody has a real-time picture of yield.</p>\n\n<p>\u2022 Production and QC reporting at month-end eats days of a supervisor\u2019s time that should be spent on the floor, not in Excel.</p>\n\n<p>On their own, none of these look like a problem. Together they are a standing headcount cost, paid every month, for work that produces nothing. The same hours put back into production would show up directly in output.</p>\n\n<p>We build the fix for one of them first, free. You pay only when it is working in your business. No software license, nobody new to hire, and no new process for your team to run.</p>\n\n<p>Your competitors are already doing this. Every month it stays manual is a month they spend shipping more with the same headcount you have today.</p>\n\n<p>If you\u2019d like to explore what this could look like, feel free to grab a convenient time here: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n',
    2: '<p>Hi {{Name}},</p>\n\n<p>Just checking in one more time.</p>\n\n<p>Many electrical and electronic manufacturing businesses assume that cutting QC and compliance admin requires new software or a large transformation project. In reality, automating one repetitive process such as certificate chasing, non-conformance logging, or production reporting saves hours every week, and your team spends that time on output instead of paperwork.</p>\n\n<p>That capacity does not disappear, it moves. The people doing that work today go back to running the line, which is where your return actually comes from.</p>\n\n<p>We\u2019re happy to identify one opportunity and build it for you at no cost. Nothing changes in how your team works, the output just arrives. You only move forward if it delivers value.</p>\n\n<p>The gap between businesses running on AI and businesses running on people isn\u2019t closing, it\u2019s widening. It widens quietly, which is what makes it easy to miss until a competitor prices or delivers in a way you cannot match.</p>\n\n<p>If you\u2019d like to explore one automation opportunity for your business, you can grab a slot on my calendar: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n',
    3: '<p>Hi {{Name}},</p>\n\n<p>I understand this may not be the right time, so I\u2019ll close the loop for now.</p>\n\n<p>If cutting QC and compliance admin isn\u2019t a priority today, no worries. I just wanted to leave this with you in case it becomes relevant down the road.</p>\n\n<p>Whenever you\u2019re looking at practical AI automation that delivers measurable results without upfront cost, extra software or a new process to manage, we\u2019d be happy to help. We hand over the outcome, not another system for your team to run.</p>\n\n<p>AI in operations isn\u2019t a trend anymore, it\u2019s becoming the baseline. The businesses adopting it now won\u2019t simply be doing the same work faster. They will be operating on a cost base the rest of the market cannot match, and by the time that shows up in pricing it is difficult to catch.</p>\n\n<p>If you\u2019d ever like to chat, you can grab a time directly on my calendar here: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n',
  },
  Medical: {
    1: '<p>Hi {{Name}},</p>\n\n<p>Following up briefly, because the expensive part is usually not the part anyone is looking at.</p>\n\n<p>The real cost in medical device manufacturing businesses isn\u2019t the obvious spend. It is the work that never appears on a line item:</p>\n\n<p>\u2022 Batch and device history record review happens manually, page by page, which slows down release and ties up quality staff.</p>\n\n<p>\u2022 Complaint handling and CAPA logging get tracked across spreadsheets and email, making trend analysis for audits slow and error prone.</p>\n\n<p>\u2022 Preparing evidence for internal and external audits consumes days of engineering time that should be spent on design and validation.</p>\n\n<p>On their own, none of these look like a problem. Together they are a standing headcount cost, paid every month, for work that produces nothing. The same hours put back into design and quality would show up directly in throughput.</p>\n\n<p>We build the fix for one of them first, free. You pay only when it is working in your business. No software license, nobody new to hire, and no new process for your team to run.</p>\n\n<p>Your competitors are already doing this. Every month it stays manual is a month they spend releasing batches faster while the rest of the market is still buried in paperwork.</p>\n\n<p>If you\u2019d like to explore what this could look like, feel free to grab a convenient time here: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n',
    2: '<p>Hi {{Name}},</p>\n\n<p>Just checking in one more time.</p>\n\n<p>Many medical device manufacturing businesses assume that cutting quality and regulatory admin requires new software or a large transformation project. In reality, automating one repetitive process such as batch record review, complaint and CAPA logging, or audit evidence gathering saves hours every week, and your team spends that time on design and validation instead of paperwork.</p>\n\n<p>That capacity does not disappear, it moves. The people doing that work today go back to design controls and product quality, which is where your return actually comes from.</p>\n\n<p>We\u2019re happy to identify one opportunity and build it for you at no cost. Nothing changes in how your team works, the output just arrives. You only move forward if it delivers value.</p>\n\n<p>The gap between businesses running on AI and businesses running on people isn\u2019t closing, it\u2019s widening. It widens quietly, which is what makes it easy to miss until a competitor clears audits or releases product in a way you cannot match.</p>\n\n<p>If you\u2019d like to explore one automation opportunity for your business, you can grab a slot on my calendar: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n',
    3: '<p>Hi {{Name}},</p>\n\n<p>I understand this may not be the right time, so I\u2019ll close the loop for now.</p>\n\n<p>If cutting quality and regulatory admin isn\u2019t a priority today, no worries. I just wanted to leave this with you in case it becomes relevant down the road.</p>\n\n<p>Whenever you\u2019re looking at practical AI automation that delivers measurable results without upfront cost, extra software or a new process to manage, we\u2019d be happy to help. We hand over the outcome, not another system for your team to run.</p>\n\n<p>AI in operations isn\u2019t a trend anymore, it\u2019s becoming the baseline. The businesses adopting it now won\u2019t simply be doing the same work faster. They will be operating on a cost base the rest of the market cannot match, and by the time that shows up in pricing it is difficult to catch.</p>\n\n<p>If you\u2019d ever like to chat, you can grab a time directly on my calendar here: <a href="https://uniligence.com/discovery-call">Grab a slot</a></p>\n\n<p>Best,<br>Mahidhar<br>Growth &amp; Operations<br><a href="https://uniligence.com/">Uniligence</a></p>\n',
  },
};

const results = [];
for (const item of $input.all()) {
  const d = item.json;
  const category = (d["Category"] || "").trim();
  const stage = d["nextFollowUp"];
  const templatesForCategory = CONTENT_MAP[category];
  let message = templatesForCategory[stage] || "";

  message = message
    .replace(/{{Name}}/g, d["Name"] || "")
    .replace(/{{Company}}/g, d["Company"] || "")
    .replace(/{{City}}/g, d["City"] || "");

  results.push({ json: { ...d, message }, pairedItem: item.pairedItem });
}

return results;
